{% set name = "google-cloud-billing-budgets" %}
{% set version = "1.14.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 9164ccb243f73334ae070cc9373d276a201542ac506e82cbb65ff1ae2c4b359e

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - google-api-core >=1.34.1,<3.0.0dev,!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,!=2.10.*
    - google-api-core-grpc
    - google-auth >=2.14.1,<3.0.0dev,!=2.24.0,!=2.25.0
    # use Python 3.11 version constraint to keep package noarch
    - proto-plus >=1.22.3,<2.0.0dev
    - protobuf >=3.20.2,<6.0.0dev,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5

test:
  requires:
    - python
    - pip
  imports:
    - google
    - google.api_core
    - google.cloud
    - google.cloud.billing
    - grpc
  commands:
    - python -m pip check

about:
  home: https://github.com/googleapis/google-cloud-python/tree/main/packages/google-cloud-billing-budgets
  summary: Python Client for Google Cloud Billing Budget
  doc_url: https://googleapis.dev/python/billingbudgets/latest/index.html
  dev_url: https://github.com/googleapis/google-cloud-python/tree/main/packages/google-cloud-billing-budgets
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tpdownes
    - tswast
